substitutions:
  _FIREBASE_PROJECT_ID: longtranhhodau-fest
  _HOSTING_TARGET: hosting

steps:
  - name: node:22
    entrypoint: bash
    args:
      - -c
      - cd frontend && npm ci && npm run build

  - name: node:22
    entrypoint: bash
    args:
      - -c
      - cd frontend && npm i -g firebase-tools && firebase deploy --project ${_FIREBASE_PROJECT_ID} --only ${_HOSTING_TARGET}

options:
  logging: CLOUD_LOGGING_ONLY
