substitutions:
  _FIREBASE_PROJECT_ID: replace-with-your-firebase-project-id

steps:
  - name: node:22
    entrypoint: bash
    args:
      - -c
      - cd frontend && npm ci && npm run build

  - name: node:22
    entrypoint: bash
    args:
      - -c
      - cd frontend && npm i -g firebase-tools && firebase deploy --project ${_FIREBASE_PROJECT_ID} --only hosting

options:
  logging: CLOUD_LOGGING_ONLY
